### ISSUE TITLE
feature/004 Add an healtcheck.sh bash instructions file that ensures all services are up and running

### ISSUE THREAD

**Issue by ghost** [Mzack9999/postgresELKDockerStack#5]
- Enter into the postgres container and check that the user given in the env file can access with the corresponding password to the corresponding database.

- Enter into the elastic search container and check that the default user with the default password can launch the elastic healthcheck command and that the elastic status is green.

**Comment by ghost** [comment]
Not useful.
Application integration tests will test infrastructure.

**Comment by Mzack9999** [comment]
[DO](https://www.digitalocean.com/community/tutorials/how-to-configure-a-continuous-integration-testing-environment-with-docker-and-docker-compose-on-ubuntu-14-04) suggest to dockerize these kind of health checks
